banned_ips:
  class: sfPropelRouteCollection
  options:
    model:                BannedIps
    module:               banned
    prefix_path:          /banned
    column:               id
    with_wildcard_routes: true

news:
  class: sfPropelRouteCollection
  options:
    model:                News
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

static_pages:
  class: sfPropelRouteCollection
  options:
    model:                StaticPages
    module:               static
    prefix_path:          static
    column:               id
    with_wildcard_routes: true

film:
  class: sfPropelRouteCollection
  options:
    model:                Film
    module:               film
    prefix_path:          film
    column:               id
    with_wildcard_routes: true

film_types:
  class: sfPropelRouteCollection
  options:
    model:                FilmTypes
    module:               catalog
    prefix_path:          catalog
    column:               id
    with_wildcard_routes: true

# default rules
user_login:
  url:     /login
  param: { module: user, action: login }
user_logout:
  url:     /logout
  param: { module: user, action: logout }  

homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
