<?php


/**
 * This class defines the structure of the 'afisha' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Sat Feb 27 16:24:44 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AfishaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AfishaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('afisha');
		$this->setPhpName('Afisha');
		$this->setClassname('Afisha');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('afisha_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('EXTERNAL_ID', 'ExternalId', 'VARCHAR', false, 500, '');
		$this->addForeignKey('AFISHA_THEATER_ID', 'AfishaTheaterId', 'INTEGER', 'afisha_theater', 'ID', true, null, null);
		$this->addForeignKey('AFISHA_FILM_ID', 'AfishaFilmId', 'INTEGER', 'afisha_film', 'ID', true, null, null);
		$this->addForeignKey('AFISHA_ZAL_ID', 'AfishaZalId', 'INTEGER', 'afisha_zal', 'ID', true, null, null);
		$this->addColumn('LINK', 'Link', 'VARCHAR', false, 255, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null, null);
		$this->addColumn('DATE_BEGIN', 'DateBegin', 'TIMESTAMP', true, null, null);
		$this->addColumn('DATE_END', 'DateEnd', 'TIMESTAMP', true, null, null);
		$this->addColumn('TIMES', 'Times', 'LONGVARCHAR', false, null, null);
		$this->addColumn('PRICES', 'Prices', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('AfishaTheater', 'AfishaTheater', RelationMap::MANY_TO_ONE, array('afisha_theater_id' => 'id', ), null, null);
    $this->addRelation('AfishaFilm', 'AfishaFilm', RelationMap::MANY_TO_ONE, array('afisha_film_id' => 'id', ), null, null);
    $this->addRelation('AfishaZal', 'AfishaZal', RelationMap::MANY_TO_ONE, array('afisha_zal_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('AfishaTime', 'AfishaTime', RelationMap::ONE_TO_MANY, array('id' => 'afisha_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // AfishaTableMap
