<?php


/**
 * This class adds structure of 'film' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Nov 15 12:35:41 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FilmMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FilmMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FilmPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FilmPeer::TABLE_NAME);
		$tMap->setPhpName('Film');
		$tMap->setClassname('Film');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'users', 'ID', true, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, 500);

		$tMap->addColumn('ORIGINAL_TITLE', 'OriginalTitle', 'VARCHAR', true, 500);

		$tMap->addColumn('NORMAL_LOGO', 'NormalLogo', 'VARCHAR', false, 255);

		$tMap->addColumn('THUMB_LOGO', 'ThumbLogo', 'VARCHAR', false, 255);

		$tMap->addColumn('URL', 'Url', 'VARCHAR', false, 500);

		$tMap->addColumn('PUB_YEAR', 'PubYear', 'INTEGER', false, null);

		$tMap->addColumn('DIRECTOR', 'Director', 'VARCHAR', false, 255);

		$tMap->addColumn('CAST', 'Cast', 'VARCHAR', false, 1000);

		$tMap->addColumn('ABOUT', 'About', 'LONGVARCHAR', false, null);

		$tMap->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 500);

		$tMap->addColumn('DURATION', 'Duration', 'VARCHAR', false, 500);

		$tMap->addColumn('FILE_INFO', 'FileInfo', 'LONGVARCHAR', false, null);

		$tMap->addColumn('IS_VISIBLE', 'IsVisible', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_PRIVATE', 'IsPrivate', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_PUBLIC', 'IsPublic', 'BOOLEAN', true, null);

		$tMap->addColumn('UPDATE_DATA', 'UpdateData', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // FilmMapBuilder
