<?php

/**
 * Base class that represents a row from the 'afisha_zal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Jan 11 22:42:37 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAfishaZal extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AfishaZalPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the afisha_theater_id field.
	 * @var        int
	 */
	protected $afisha_theater_id;

	/**
	 * The value for the afisha_id field.
	 * @var        int
	 */
	protected $afisha_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * @var        AfishaTheater
	 */
	protected $aAfishaTheater;

	/**
	 * @var        Afisha
	 */
	protected $aAfisha;

	/**
	 * @var        array AfishaZalTime[] Collection to store aggregation of AfishaZalTime objects.
	 */
	protected $collAfishaZalTimes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAfishaZalTimes.
	 */
	private $lastAfishaZalTimeCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AfishaZalPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [afisha_theater_id] column value.
	 * 
	 * @return     int
	 */
	public function getAfishaTheaterId()
	{
		return $this->afisha_theater_id;
	}

	/**
	 * Get the [afisha_id] column value.
	 * 
	 * @return     int
	 */
	public function getAfishaId()
	{
		return $this->afisha_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     AfishaZal The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AfishaZalPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [afisha_theater_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AfishaZal The current object (for fluent API support)
	 */
	public function setAfishaTheaterId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->afisha_theater_id !== $v) {
			$this->afisha_theater_id = $v;
			$this->modifiedColumns[] = AfishaZalPeer::AFISHA_THEATER_ID;
		}

		if ($this->aAfishaTheater !== null && $this->aAfishaTheater->getId() !== $v) {
			$this->aAfishaTheater = null;
		}

		return $this;
	} // setAfishaTheaterId()

	/**
	 * Set the value of [afisha_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AfishaZal The current object (for fluent API support)
	 */
	public function setAfishaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->afisha_id !== $v) {
			$this->afisha_id = $v;
			$this->modifiedColumns[] = AfishaZalPeer::AFISHA_ID;
		}

		if ($this->aAfisha !== null && $this->aAfisha->getId() !== $v) {
			$this->aAfisha = null;
		}

		return $this;
	} // setAfishaId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     AfishaZal The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = AfishaZalPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->afisha_theater_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->afisha_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->title = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = AfishaZalPeer::NUM_COLUMNS - AfishaZalPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AfishaZal object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAfishaTheater !== null && $this->afisha_theater_id !== $this->aAfishaTheater->getId()) {
			$this->aAfishaTheater = null;
		}
		if ($this->aAfisha !== null && $this->afisha_id !== $this->aAfisha->getId()) {
			$this->aAfisha = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AfishaZalPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AfishaZalPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAfishaTheater = null;
			$this->aAfisha = null;
			$this->collAfishaZalTimes = null;
			$this->lastAfishaZalTimeCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AfishaZalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAfishaZal:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				AfishaZalPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAfishaZal:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AfishaZalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAfishaZal:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAfishaZal:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				AfishaZalPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAfishaTheater !== null) {
				if ($this->aAfishaTheater->isModified() || $this->aAfishaTheater->isNew()) {
					$affectedRows += $this->aAfishaTheater->save($con);
				}
				$this->setAfishaTheater($this->aAfishaTheater);
			}

			if ($this->aAfisha !== null) {
				if ($this->aAfisha->isModified() || $this->aAfisha->isNew()) {
					$affectedRows += $this->aAfisha->save($con);
				}
				$this->setAfisha($this->aAfisha);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AfishaZalPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AfishaZalPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AfishaZalPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAfishaZalTimes !== null) {
				foreach ($this->collAfishaZalTimes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAfishaTheater !== null) {
				if (!$this->aAfishaTheater->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAfishaTheater->getValidationFailures());
				}
			}

			if ($this->aAfisha !== null) {
				if (!$this->aAfisha->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAfisha->getValidationFailures());
				}
			}


			if (($retval = AfishaZalPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAfishaZalTimes !== null) {
					foreach ($this->collAfishaZalTimes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AfishaZalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getAfishaTheaterId();
				break;
			case 2:
				return $this->getAfishaId();
				break;
			case 3:
				return $this->getTitle();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AfishaZalPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getAfishaTheaterId(),
			$keys[2] => $this->getAfishaId(),
			$keys[3] => $this->getTitle(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AfishaZalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setAfishaTheaterId($value);
				break;
			case 2:
				$this->setAfishaId($value);
				break;
			case 3:
				$this->setTitle($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AfishaZalPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setAfishaTheaterId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAfishaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitle($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AfishaZalPeer::DATABASE_NAME);

		if ($this->isColumnModified(AfishaZalPeer::ID)) $criteria->add(AfishaZalPeer::ID, $this->id);
		if ($this->isColumnModified(AfishaZalPeer::AFISHA_THEATER_ID)) $criteria->add(AfishaZalPeer::AFISHA_THEATER_ID, $this->afisha_theater_id);
		if ($this->isColumnModified(AfishaZalPeer::AFISHA_ID)) $criteria->add(AfishaZalPeer::AFISHA_ID, $this->afisha_id);
		if ($this->isColumnModified(AfishaZalPeer::TITLE)) $criteria->add(AfishaZalPeer::TITLE, $this->title);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AfishaZalPeer::DATABASE_NAME);

		$criteria->add(AfishaZalPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AfishaZal (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setAfishaTheaterId($this->afisha_theater_id);

		$copyObj->setAfishaId($this->afisha_id);

		$copyObj->setTitle($this->title);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAfishaZalTimes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAfishaZalTime($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AfishaZal Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AfishaZalPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AfishaZalPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AfishaTheater object.
	 *
	 * @param      AfishaTheater $v
	 * @return     AfishaZal The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAfishaTheater(AfishaTheater $v = null)
	{
		if ($v === null) {
			$this->setAfishaTheaterId(NULL);
		} else {
			$this->setAfishaTheaterId($v->getId());
		}

		$this->aAfishaTheater = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AfishaTheater object, it will not be re-added.
		if ($v !== null) {
			$v->addAfishaZal($this);
		}

		return $this;
	}


	/**
	 * Get the associated AfishaTheater object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AfishaTheater The associated AfishaTheater object.
	 * @throws     PropelException
	 */
	public function getAfishaTheater(PropelPDO $con = null)
	{
		if ($this->aAfishaTheater === null && ($this->afisha_theater_id !== null)) {
			$this->aAfishaTheater = AfishaTheaterPeer::retrieveByPk($this->afisha_theater_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAfishaTheater->addAfishaZals($this);
			 */
		}
		return $this->aAfishaTheater;
	}

	/**
	 * Declares an association between this object and a Afisha object.
	 *
	 * @param      Afisha $v
	 * @return     AfishaZal The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAfisha(Afisha $v = null)
	{
		if ($v === null) {
			$this->setAfishaId(NULL);
		} else {
			$this->setAfishaId($v->getId());
		}

		$this->aAfisha = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Afisha object, it will not be re-added.
		if ($v !== null) {
			$v->addAfishaZal($this);
		}

		return $this;
	}


	/**
	 * Get the associated Afisha object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Afisha The associated Afisha object.
	 * @throws     PropelException
	 */
	public function getAfisha(PropelPDO $con = null)
	{
		if ($this->aAfisha === null && ($this->afisha_id !== null)) {
			$this->aAfisha = AfishaPeer::retrieveByPk($this->afisha_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAfisha->addAfishaZals($this);
			 */
		}
		return $this->aAfisha;
	}

	/**
	 * Clears out the collAfishaZalTimes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAfishaZalTimes()
	 */
	public function clearAfishaZalTimes()
	{
		$this->collAfishaZalTimes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAfishaZalTimes collection (array).
	 *
	 * By default this just sets the collAfishaZalTimes collection to an empty array (like clearcollAfishaZalTimes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAfishaZalTimes()
	{
		$this->collAfishaZalTimes = array();
	}

	/**
	 * Gets an array of AfishaZalTime objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AfishaZal has previously been saved, it will retrieve
	 * related AfishaZalTimes from storage. If this AfishaZal is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AfishaZalTime[]
	 * @throws     PropelException
	 */
	public function getAfishaZalTimes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AfishaZalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAfishaZalTimes === null) {
			if ($this->isNew()) {
			   $this->collAfishaZalTimes = array();
			} else {

				$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

				AfishaZalTimePeer::addSelectColumns($criteria);
				$this->collAfishaZalTimes = AfishaZalTimePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

				AfishaZalTimePeer::addSelectColumns($criteria);
				if (!isset($this->lastAfishaZalTimeCriteria) || !$this->lastAfishaZalTimeCriteria->equals($criteria)) {
					$this->collAfishaZalTimes = AfishaZalTimePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAfishaZalTimeCriteria = $criteria;
		return $this->collAfishaZalTimes;
	}

	/**
	 * Returns the number of related AfishaZalTime objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AfishaZalTime objects.
	 * @throws     PropelException
	 */
	public function countAfishaZalTimes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AfishaZalPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAfishaZalTimes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

				$count = AfishaZalTimePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

				if (!isset($this->lastAfishaZalTimeCriteria) || !$this->lastAfishaZalTimeCriteria->equals($criteria)) {
					$count = AfishaZalTimePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAfishaZalTimes);
				}
			} else {
				$count = count($this->collAfishaZalTimes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AfishaZalTime object to this object
	 * through the AfishaZalTime foreign key attribute.
	 *
	 * @param      AfishaZalTime $l AfishaZalTime
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAfishaZalTime(AfishaZalTime $l)
	{
		if ($this->collAfishaZalTimes === null) {
			$this->initAfishaZalTimes();
		}
		if (!in_array($l, $this->collAfishaZalTimes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAfishaZalTimes, $l);
			$l->setAfishaZal($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AfishaZal is new, it will return
	 * an empty collection; or if this AfishaZal has previously
	 * been saved, it will retrieve related AfishaZalTimes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AfishaZal.
	 */
	public function getAfishaZalTimesJoinAfisha($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AfishaZalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAfishaZalTimes === null) {
			if ($this->isNew()) {
				$this->collAfishaZalTimes = array();
			} else {

				$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

				$this->collAfishaZalTimes = AfishaZalTimePeer::doSelectJoinAfisha($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AfishaZalTimePeer::AFISHA_ZAL_ID, $this->id);

			if (!isset($this->lastAfishaZalTimeCriteria) || !$this->lastAfishaZalTimeCriteria->equals($criteria)) {
				$this->collAfishaZalTimes = AfishaZalTimePeer::doSelectJoinAfisha($criteria, $con, $join_behavior);
			}
		}
		$this->lastAfishaZalTimeCriteria = $criteria;

		return $this->collAfishaZalTimes;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAfishaZalTimes) {
				foreach ((array) $this->collAfishaZalTimes as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAfishaZalTimes = null;
			$this->aAfishaTheater = null;
			$this->aAfisha = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAfishaZal:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAfishaZal::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAfishaZal
