<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/31 20:52:03

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=symfony_films',
  'username' => 'films_user',
  'password' => 'axd23PKWrYmKthqq',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
