<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/08/31 20:52:04
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
