# default values
all:
  user_remember_key_expiration_age:  7776000
  remember_cookie_name: 'userRememberCookies'
  pages:
    main_page: 30
    catalog_page: 30  
  films:
    poster_size: 5242880
    max_gallery: 10
    gallery_size: 5242880
    max_links: 100
