# default values
all:
  user_remember_key_expiration_age:  7776000
  remember_cookie_name: 'userRememberCookies'
  pages:
    main_page: 30
    catalog_page: 30
    comments_page: 50
    all_comments_page: 100
  films:
    poster_size: 5242880
    min_gallery: 3
    max_gallery: 10
    gallery_size: 5242880
    min_links: 1
    max_links: 100
  search:
    method: sphinx #default lucene
    limit: 50
  last_comments: 5
  films_top:
    new: 6
  users_top_film: 15
  sitemap:
    limit: 2000
  
  #sphinx options
  sphinx_search:
    indexer: /opt/sphinx/bin/indexer
    searchd: /opt/sphinx/bin/searchd
    config: /config/sphinx.conf
  
  #integration
  integration:
    is_verlihub: true
    verlihub_config:
      host: localhost
      user: verlihub_user
      password: q2mBq6Qv2c3Zsjnb
      database: verlihub_db
    is_jabber: true
    jabber_server: 127.0.0.1:9090
    jabber_domain: leo-asus
    is_twitter: true
    twitter_username: username
    twitter_password: pass
    
  #captcha
  sf_crypto_captcha:
    char_max_rot_angle: 60
    chars_used: '0123456789'
    brush_size: 1
    effect_blur: true
    effect_grayscale: true
    noise_min_lines: 3
    noise_max_lines: 6

  google_analytics:
    code: UA-10000-01