# default values
all:
  user_remember_key_expiration_age:  7776000
  remember_cookie_name: 'userRememberCookies'
  pages:
    main_page: 30
    catalog_page: 30
    comments_page: 50 
  films:
    poster_size: 5242880
    min_gallery: 3
    max_gallery: 10
    gallery_size: 5242880
    min_links: 1
    max_links: 100
