# default values
all:
  user_remember_key_expiration_age:  7776000
  remember_cookie_name: 'userRememberCookies'
  pages:
    main_page: 30
    catalog_page: 30
    comments_page: 50 
  films:
    poster_size: 5242880
    min_gallery: 3
    max_gallery: 10
    gallery_size: 5242880
    min_links: 1
    max_links: 100
  search:
    method: sphinx #default lucene
    limit: 50
  last_comments: 5
    
    
  #captcha
  sf_crypto_captcha:
    char_max_rot_angle: 60
    chars_used: '0123456789'
    brush_size: 1
    effect_blur: true
    effect_grayscale: true
    noise_min_lines: 3
    noise_max_lines: 6
