banned:
  class: BannedFilter

rendering: ~

remember:
  class: LoginFilter

mobile:
  class: MobileFilter
  param:
    mobile_agents:
     - 2.0 MMP
     - 240x320
     - 400X240
     - AvantGo
     - BlackBerry
     - Blazer
     - Cellphone
     - Danger
     - DoCoMo
     - Elaine/3.0
     - EudoraWeb
     - Googlebot-Mobile
     - hiptop
     - IEMobile
     - KYOCERA/WX310K
     - LG/U990
     - MIDP-2
     - MMEF20
     - MOT-V
     - NetFront
     - Newt
     - Nintendo Wii
     - Nitro
     - Nokia
     - Opera Mini
     - Palm
     - PlayStation Portable
     - portalmmm
     - Proxinet
     - ProxiNet
     - SHARP-TQ-GX10
     - SHG-i900
     - Small
     - SonyEricsson
     - Symbian OS
     - SymbianOS
     - TS21i-10
     - UP.Browser
     - UP.Link
     - Windows CE
     - WinWAP
     - YahooSeeker/M1A1-R2D2
     - iPhone
     - iPod
     - Android
     - LG-TU915 Obigo
     - LGE VX
     - webOS

security: ~

# insert your own filters here

cache:     ~
execution: ~
