default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    description:  Coocoorooza - ресурс, обеспечивает быстрый обмен фильмами и сериалами, информацией про новинки кино и индустрии.
    keywords:     Coocoorooza, кукуруза, фильмы, сериалы, лучшее
    language:     ru
    robots:       index, follow

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
