default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     ru
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [prototype.min.js, effects.min.js, controls.min.js, frontend_less_routes_dev.js, application.js]

  has_layout:     on
  layout:         layout
