profile:
  is_secure:   true    # The update action is only for authenticated
list_unpublic_films:
  is_secure:   true
logout:
  is_secure:   true    # Only for authenticated users
all:
  is_secure:  false
