profile:
  is_secure:   on    # The update action is only for authenticated
list_unpublic_films:
  is_secure:   true
logout:
  is_secure:   on    # Only for authenticated users
all:
  is_secure:  false
