profile:
  is_secure:   true    # The update action is only for authenticated
change_password:
  is_secure:   true    # The update action is only for authenticated  
unpublic_films:
  is_secure:   true
unvisible_films:
  is_secure:   true
  credentials: [[ admin, super_admin, moder ]]
logout:
  is_secure:   true    # Only for authenticated users
all:
  is_secure:  false
