<?php

require 'lib/model/om/BaseAfishaTheater.php';


/**
 * Skeleton subclass for representing a row from the 'afisha_theater' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun Jan 10 02:06:29 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaTheater extends BaseAfishaTheater {

} // AfishaTheater

sfPropelBehavior::add('AfishaTheater', array(
	'viewCacheObserver' => array(
		'cache' => array(
			'afisha/cinema?id=#{id}',
			'afisha/cinema?day=*&id=#{id}&month=*&year=*'
		),
		'variables' => array(
			'id' => 'getId'
		),
		'criteria' => array(
			//'getIsVisible' => true,
			//'getIsPublic' => true
		)
	)
));