<?php

require 'lib/model/om/BaseAfishaFilm.php';


/**
 * Skeleton subclass for representing a row from the 'afisha_film' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Jan 15 23:07:01 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaFilm extends BaseAfishaFilm {

	/**
	 * Initializes internal state of AfishaFilm object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // AfishaFilm

sfPropelBehavior::add('AfishaFilm', array(
	'viewCacheObserver' => array(
		'cache' => array(
			'afisha/film?id=#{id}',
			'afisha/film?day=*&id=#{id}&month=*&year=*',
			'afisha/film?day=*&id=#{id}&month=*&year=*&city_id=*'
		),
		'variables' => array(
			'id' => 'getId'
		),
		'criteria' => array(
			//'getIsVisible' => true,
			//'getIsPublic' => true
		)
	)
));
