<?php

require 'lib/model/om/BaseAfishaZalDatePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'afisha_zal_date' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jan 16 01:47:40 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaZalDatePeer extends BaseAfishaZalDatePeer {

	static public function getByTimeAndAfisha($afisha_id, $date_begin, $date_end) {
		$criteria = new Criteria();
		$criteria->add(self::AFISHA_ID, $afisha_id);
		$criteria->add(self::DATE_BEGIN, $date_begin);
		$criteria->add(self::DATE_END, $date_end);
    	return self::doSelectOne($criteria);
    }
	
} // AfishaZalDatePeer
