<?php

require 'lib/model/om/BaseAfishaZalDate.php';


/**
 * Skeleton subclass for representing a row from the 'afisha_zal_date' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jan 16 01:47:40 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaZalDate extends BaseAfishaZalDate {

} // AfishaZalDate
