<?php

require 'lib/model/om/BaseAfishaTimePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'afisha_time' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jan 16 23:29:54 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaTimePeer extends BaseAfishaTimePeer {

} // AfishaTimePeer
