<?php

require 'lib/model/om/BaseAfishaZalTime.php';


/**
 * Skeleton subclass for representing a row from the 'afisha_zal_time' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun Jan 10 02:06:30 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaZalTime extends BaseAfishaZalTime {

} // AfishaZalTime
