<?php

require 'lib/model/om/BaseAfishaTheaterPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'afisha_theater' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun Jan 10 02:06:29 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaTheaterPeer extends BaseAfishaTheaterPeer {

	static public function getByExternalId($external_id) {
		$criteria = new Criteria();
		$criteria->add(self::EXTERNAL_ID, $external_id);
    	return self::doSelectOne($criteria);
    }
	
} // AfishaTheaterPeer
