<?php

require 'lib/model/om/BaseAfishaCountryPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'afisha_country' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Jan 15 19:29:09 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaCountryPeer extends BaseAfishaCountryPeer {

} // AfishaCountryPeer
