<?php

require 'lib/model/om/BaseAfishaCountry.php';


/**
 * Skeleton subclass for representing a row from the 'afisha_country' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Jan 15 19:29:09 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AfishaCountry extends BaseAfishaCountry {

	/**
	 * Initializes internal state of AfishaCountry object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // AfishaCountry
