<?php

require 'lib/model/om/BaseFilmTrailerPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'film_trailer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Jan 28 22:11:21 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmTrailerPeer extends BaseFilmTrailerPeer {
	
	public static function getCountByFilm($film_id){
    	$criteria = new Criteria();
	    $criteria->add(self::FILM_ID, $film_id);
	    return self::doCount($criteria);
	}

} // FilmTrailerPeer
