<?php

require 'lib/model/om/BaseFilmNews.php';


/**
 * Skeleton subclass for representing a row from the 'film_news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Feb  5 14:14:19 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmNews extends BaseFilmNews {

	/**
	 * Initializes internal state of FilmNews object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // FilmNews
