<?php

require 'lib/model/om/BaseFilmNewsPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'film_news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Feb  5 14:14:19 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmNewsPeer extends BaseFilmNewsPeer {

} // FilmNewsPeer
