<?php

require 'lib/model/om/BaseFilmTrailer.php';


/**
 * Skeleton subclass for representing a row from the 'film_trailer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Jan 28 22:11:21 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmTrailer extends BaseFilmTrailer {

	/**
	 * Initializes internal state of FilmTrailer object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function save(PropelPDO $con = null) {
		if ($this->isNew()){
			$this->setSort(FilmTrailerPeer::getCountByFilm($this->getFilm()->getId()));
		}
		return parent::save($con);
	}

} // FilmTrailer

sfPropelBehavior::add('FilmTrailer', array(
	'viewCacheObserver' => array(
		'belongs_to_depend' => array(
			'getFilm'
		)
	)
));