<?php

require 'lib/model/om/BaseFilmTotalRatingPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'film_total_rating' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Jan 19 13:05:32 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmTotalRatingPeer extends BaseFilmTotalRatingPeer {

	static public function getTopFilms(){
		$criteria = new Criteria();
		$criteria->setLimit(sfConfig::get('app_films_top_limit', 10));
		$criteria->addDescendingOrderByColumn(self::TOTAL_RATING);
		return self::doSelectJoinFilm($criteria);
	}
	
} // FilmTotalRatingPeer
