<?php

require 'lib/model/om/BaseUserPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Вто 01 Июн 2010 01:49:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserPeer extends BaseUserPeer {

} // UserPeer
