dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=symfony_films'
      username: films_user
      password: axd23PKWrYmKthqq
      encoding: utf8
      persistent: true
      pooling: true
