propel:
  users:
    id:               ~
    login:            { type: varchar(100), required: true, index: unique }
    password:         { type: varchar(100), required: true }
    email:            { type: varchar(100), required: true, index: unique }
    website_blog:     { type: varchar(500) }
    avatar:           { type: varchar(500) }
    about:            { type: longvarchar }
    last_login:       { type: timestamp }
    is_active:        { type: boolean, required: true, default: 1 }
    is_super_admin:   { type: boolean, required: true, default: 0 }
    created_at:       ~
    updated_at:       ~
  
  users_group:
    id:             ~
    name:           { type: varchar, size: 255, required: true, index: unique }
    description:    { type: longvarchar }
    
  users_users_group:
    user_id:        { type: integer, primaryKey: true, required: true, foreignTable: users, foreignReference: id, onDelete: cascade }
    group_id:       { type: integer, primaryKey: true, required: true, foreignTable: users_group, foreignReference: id, onDelete: cascade }
    
  users_remember_key:
    user_id:        { type: integer, primaryKey: true, required: true, foreignTable: users, foreignReference: id, onDelete: cascade }
    remember_key:   { type: varchar, size: 32 }
    ip_address:     { type: varchar, size: 50, primaryKey: true }
    created_at:     ~
    
  film:
    id:               ~
    user_id:          { type: integer, foreignTable: users, foreignReference: id, required: true }
    title:            { type: varchar(500), required: true }
    original_title:   { type: varchar(500), required: true }
    normal_logo:      { type: varchar(255) }
    thumb_logo:       { type: varchar(255) } 
    url:              { type: varchar(500) }
    pub_year:         { type: integer }
    director:         { type: varchar(255) }
    cast:             { type: varchar(1000) }
    about:            { type: longvarchar }
    country:          { type: varchar(500) }
    duration:         { type: varchar(500) }
    file_info:        { type: longvarchar }
    is_visible:       { type: boolean, required: true, default: 1 }
    is_private:       { type: boolean, required: true, default: 0 }
    is_public:        { type: boolean, required: true, default: 0 }
    update_data:      { type: timestamp }
    created_at:       ~
    updated_at:       ~
    
  film_links:
    id:               ~
    film_id:          { type: integer, foreignTable: film, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    title:            { type: varchar(200), required: true }
    url:              { type: varchar(500), required: true }
    sort:             { type: integer, default: 0 }
    created_at:       ~
    updated_at:       ~ 
    
  film_types:
    id:               ~
    title:            { type: varchar(500), required: true }
    url:              { type: varchar(500), required: true }
    logo:             { type: varchar(500), required: true }
    description:      { type: longvarchar }
    is_visible:       { type: boolean, required: true, default: 1 }
    is_not_main:      { type: boolean, required: true, default: 0 }
    created_at:       ~
    
  film_raiting:
    id:               ~
    film_id:          { type: integer, foreignTable: film, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    user_id:          { type: integer, foreignTable: users, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    raiting:          { type: integer, required: true, default: 1 }
    
  film_gallery:
    id:               ~
    film_id:          { type: integer, foreignTable: film, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    thumb_img:        { type: varchar(500), required: true }
    normal_img:       { type: varchar(500), required: true }
    sort:             { type: integer, default: 0 }
    
  film_film_types:
    film_id:          { type: integer, foreignTable: film, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
    film_genre_id:    { type: integer, foreignTable: film_types, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }

  comments:
   id:               ~
   user_id:          { type: integer, foreignTable: users, foreignReference: id, required: true }
   film_id:          { type: integer, foreignTable: film, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
   description:      { type: longvarchar }
   created_at:       ~
   updated_at:       ~
   
  messages:
   id:               ~
   user_id:          { type: integer, foreignTable: users, foreignReference: id, required: true }
   message_type:     { type: integer, required: true }
   description:      { type: longvarchar }
   created_at:       ~
   updated_at:       ~
     
  user_friends:
   user_id:          { type: integer, foreignTable: users, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
   friend_id:        { type: integer, foreignTable: users, foreignReference: id, required: true, onDelete: cascade }
   commit:           { type: boolean, required: true, default: 0 }
    
  news:
   id:              ~
   user_id:         { type: integer, foreignTable: users, foreignReference: id, required: true }
   title:           { type: varchar(500), required: true }
   url:             { type: varchar(500) }
   description:     { type: longvarchar }
   created_at:      ~
   updated_at:      ~
     
  afisha:
   id:              ~
   user_id:         { type: integer, foreignTable: users, foreignReference: id, required: true }
   title:           { type: varchar(500), required: true }
   normal_logo:     { type: varchar(255) }
   thumb_logo:      { type: varchar(255) }
   description:     { type: longvarchar }
   created_at:      ~
   updated_at:      ~
     
  static_pages:
   id:              ~
   title:           { type: varchar(500), required: true }
   url:             { type: varchar(500) }
   sort:            { type: integer, default: 0 }
   description:     { type: longvarchar }
   is_visible:      { type: boolean, required: true, default: 1 }
   created_at:      ~
   updated_at:      ~  