generator:
  class: sfPropelGenerator
  param:
    model_class:           BannedIps
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              BannedIps
    plural:                BannedIpss
    route_prefix:          banned_ips
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: { label: Создать }
      fields:
        ip: { label: IP }

      list:
        title:          Забаненые
        display:        [ip]
        max_per_page:   10
        sort:           [ip, asc]
        batch_actions:
          _delete: { label: Удалить }
        object_actions:
          _edit:       { label: Редактировать }
          _delete:     { label: Удалить, confirm: "Уверены, что хотите удалить?" }
        actions:
          _new: { label: Создать }

      filter:
        display: [ip]
        class: false

      form: ~
      edit:
        title: Редактировать забаненого по %%ip%%
      new: 
        title: Забанить новичка
