_latest:
  enabled:     true
  lifetime:    2592000 # 30 суток
index:
  enabled:     true
  lifetime:    2592000 # 30 суток  
show:
  enabled:     true
  lifetime:    2592000 # 30 суток   
all:
  with_layout: false
