index:
  enabled:     on
  lifetime:    14400 # 4 часа
cathegory_films:
  enabled:     on
  lifetime:    14400 # 4 часа
films_by_day:
  enabled:     on
  lifetime:    14400 # 4 часа
all:
  with_layout: false
