_types:
  enabled:     true
  lifetime:    2592000 # 30 суток
_film_main:
  enabled:     true
  lifetime:    2592000 # 30 суток
_topNew:
  enabled:     true
  lifetime:    2592000 # 30 суток  
_rating:
  enabled:     true
  lifetime:    2592000 # 30 суток  
all:
  with_layout: false
