_types:
  enabled:     true
  lifetime:    2592000 # 30 суток
  contextual:  true
_film_main:
  enabled:     true
  lifetime:    2592000 # 30 суток
_topNew:
  enabled:     true
  lifetime:    2592000 # 30 суток
_topRating:
  enabled:     true
  lifetime:    14400 # 4 часа (сам) 
#_rating:
#  enabled:     true
#  lifetime:    2592000 # 30 суток  
all:
  with_layout: false
