var less_routes_prefix_url = '/frontend_dev.php';
captcha_demo_path = function(){ return less_routes_prefix_url + '/captcha_demo.html'; }
captcha_refresh_path = function(random){ return less_routes_prefix_url + '/captcha/' + random + '.html'; }
captcha_path = function(){ return less_routes_prefix_url + '/captcha.html'; }
user_login_path = function(){ return less_routes_prefix_url + '/login.html'; }
user_registration_path = function(){ return less_routes_prefix_url + '/registration.html'; }
user_ajax_registration_path = function(){ return less_routes_prefix_url + '/ajax_registration.html'; }
user_registration_done_path = function(){ return less_routes_prefix_url + '/registration_done.html'; }
user_activate_path = function(id, persistence_token){ return less_routes_prefix_url + '/activate/' + id + '/' + persistence_token + '.html'; }
user_forgot_pass_path = function(){ return less_routes_prefix_url + '/forgot_pass.html'; }
user_forgot_pass_token_path = function(id, persistence_token){ return less_routes_prefix_url + '/forgot_pass_token/' + id + '/' + persistence_token + '.html'; }
user_profile_path = function(){ return less_routes_prefix_url + '/profile.html'; }
user_logout_path = function(){ return less_routes_prefix_url + '/logout.html'; }
user_films_list_path = function(){ return less_routes_prefix_url + '/unpublic_films.html'; }
user_show_path = function(id){ return less_routes_prefix_url + '/userinfo/' + id + '.html'; }
search_path = function(){ return less_routes_prefix_url + '/search.html'; }
search_auto_complete_path = function(){ return less_routes_prefix_url + '/search_auto_complete.html'; }
film_types_all_path = function(){ return less_routes_prefix_url + '/cathegory/all.html'; }
film_types_all_pages_path = function(page){ return less_routes_prefix_url + '/cathegory/all/' + page + '.html'; }
film_types_all_atom_path = function(){ return less_routes_prefix_url + '/cathegory/all.atom'; }
film_types_all_rss_path = function(){ return less_routes_prefix_url + '/cathegory/all.rss'; }
film_types_path = function(id, url){ return less_routes_prefix_url + '/cathegory/' + id + '/' + url + '.html'; }
film_types_rss_path = function(id, url){ return less_routes_prefix_url + '/cathegory/' + id + '/' + url + '.rss'; }
film_types_atom_path = function(id, url){ return less_routes_prefix_url + '/cathegory/' + id + '/' + url + '.atom'; }
film_add_step1_path = function(){ return less_routes_prefix_url + '/film/add1.html'; }
film_edit_step1_path = function(id){ return less_routes_prefix_url + '/film/edit1/' + id + '.html'; }
film_delete_step1_path = function(id){ return less_routes_prefix_url + '/film/delete1/' + id + '.html'; }
film_add_step2_path = function(id){ return less_routes_prefix_url + '/film/add2/' + id + '.html'; }
film_add_swf_step2_path = function(id){ return less_routes_prefix_url + '/film/add_swf2/' + id + '.html'; }
film_edit_step2_path = function(id){ return less_routes_prefix_url + '/film/edit2/' + id + '.html'; }
film_sort_step2_path = function(id){ return less_routes_prefix_url + '/film/sort2/' + id + '.html'; }
film_delete_gallery_path = function(id){ return less_routes_prefix_url + '/film/delete_gallery/' + id + '.html'; }
film_add_step3_path = function(id){ return less_routes_prefix_url + '/film/add3/' + id + '.html'; }
film_edit_step3_path = function(id){ return less_routes_prefix_url + '/film/edit3/' + id + '.html'; }
film_sort_step3_path = function(id){ return less_routes_prefix_url + '/film/sort3/' + id + '.html'; }
film_delete_step3_path = function(id){ return less_routes_prefix_url + '/film/delete_link/' + id + '.html'; }
film_add_final_path = function(id){ return less_routes_prefix_url + '/film/add_final/' + id + '.html'; }
film_twitter_path = function(id){ return less_routes_prefix_url + '/film/twitter/' + id + '.html'; }
film_show_path = function(id, url){ return less_routes_prefix_url + '/film/' + id + '/' + url + '.html'; }
comment_add_path = function(id){ return less_routes_prefix_url + '/comment/add/' + id + '.html'; }
comment_edit_path = function(id){ return less_routes_prefix_url + '/comment/edit/' + id + '.html'; }
comment_delete_path = function(id){ return less_routes_prefix_url + '/comment/delete/' + id + '.html'; }
comments_last_list_path = function(){ return less_routes_prefix_url + '/comments_list.html'; }
go_by_link_id_path = function(id){ return less_routes_prefix_url + '/go/' + id + '.html'; }
static_page_path = function(id, url){ return less_routes_prefix_url + '/page/' + id + '/' + url + '.html'; }
news_all_path = function(){ return less_routes_prefix_url + '/news.html'; }
news_page_all_path = function(page){ return less_routes_prefix_url + '/news/' + page + '.html'; }
news_xml_all_path = function(){ return less_routes_prefix_url + '/news.xml'; }
news_atom_all_path = function(){ return less_routes_prefix_url + '/news.xml'; }
news_one_path = function(id, url){ return less_routes_prefix_url + '/news/' + id + '/' + url + '.html'; }
afisha_path = function(){ return less_routes_prefix_url + '/afisha.html'; }
afisha_get_cities_path = function(id){ return less_routes_prefix_url + '/afisha_get_cities/' + id + '.html'; }
afisha_get_shows_path = function(id){ return less_routes_prefix_url + '/afisha/city/' + id + '.html'; }
statistic_path = function(){ return less_routes_prefix_url + '/statistic.html'; }
statistic_cathegory_films_path = function(){ return less_routes_prefix_url + '/statistic_cathegory_films.html'; }
statistic_films_by_day_path = function(){ return less_routes_prefix_url + '/statistic_films_by_day.html'; }
sitemap_path = function(){ return less_routes_prefix_url + '/sitemap.xml'; }
homepage_mobile_path = function(){ return less_routes_prefix_url + '/'; }
homepage_standard_path = function(){ return less_routes_prefix_url + '/'; }
homepage_path = function(){ return less_routes_prefix_url + '/'; }
default_index_path = function(module){ return less_routes_prefix_url + '/' + module + '.html'; }
default_path = function(module, action){ return less_routes_prefix_url + '/' + module + '/' + action + '/*.html'; }
